travis:
  secure:
    BINSTAR_TOKEN: f5vHDs6169+2ZGYG4mKxn6i1/830ekhf+bj34sBy4m4NdfNhd/ZonHx2uP275EQkRTFzdg2ovWQ48T69D7ybIfIj7HXlCDw1QYh46gd0CxNKyrpefAjOmdagS4CvZOzYyyRgLWBL1cF9wqugEeadNKoDJ/Iv/wLk5WAOcL7y6jgoKdjyFeaQGCh2L48l37TE4TMLpmSNNDQkEtEEDhdsk3UhJM44PH5N9MdU4PdNy5IpFke0tiTVHffjiU2Z6i9qsXn61Rur0+Jnq679c3hbVDcveWKDHKaE/Gx80f5SHh/r2bkoYMCBm3jww3wmmlA4A/00+e4+2Tf6366ZDioeOyp/tS7BbW+Jchc9nxysmIDazNH6sxzVl7JgT4ha4EMbfMK6Y4/Cqd8O2v8vYNHGeepCara1BBm5KiDw7L1i4eUyGjKx+47L9WesixfcKqckzxckjmidyPzttDj7c7oPLgatcEKLVV8Xe9bTqLF44kP34Z/iOa24yNAGPf6dXDBaE3nDv48isDhReZA6ISR24RWxmDFIm5FIy8xpaWU0UrHhvz6n+rpWi4J55qbj/DsCS0+iq8x3MFSUoGrwIZqFJ/KtRdeKWD8K4S5MZyC78Bvx9HzPkb5uO7EkfV9Jakrdpnm8N7vuZuJ/vsCS8s+j7QTBoUkHu4zsM3/cjuXG/Po=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
